# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_urls_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
